// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearning
{
    public partial class MLMMichael
    {
        /// <summary>
        /// model input class for MLMMichael.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"company")]
            public string Company { get; set; }

            [ColumnName(@"title")]
            public string Title { get; set; }

            [ColumnName(@"totalyearlycompensation")]
            public float Totalyearlycompensation { get; set; }

            [ColumnName(@"location")]
            public string Location { get; set; }

            [ColumnName(@"yearsofexperience")]
            public string Yearsofexperience { get; set; }

            [ColumnName(@"yearsatcompany")]
            public float Yearsatcompany { get; set; }

            [ColumnName(@"basesalary")]
            public float Basesalary { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLMMichael.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"company")]
            public float[] Company { get; set; }

            [ColumnName(@"title")]
            public float[] Title { get; set; }

            [ColumnName(@"totalyearlycompensation")]
            public float Totalyearlycompensation { get; set; }

            [ColumnName(@"location")]
            public float[] Location { get; set; }

            [ColumnName(@"yearsofexperience")]
            public float[] Yearsofexperience { get; set; }

            [ColumnName(@"yearsatcompany")]
            public float Yearsatcompany { get; set; }

            [ColumnName(@"basesalary")]
            public float Basesalary { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLMMichael.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
