﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace MachineLearning
{
    public partial class MLMMichael
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"title", @"title", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(@"yearsatcompany", @"yearsatcompany"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"company",outputColumnName:@"company"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"location",outputColumnName:@"location"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"yearsofexperience",outputColumnName:@"yearsofexperience"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"title",@"yearsatcompany",@"company",@"location",@"yearsofexperience"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(new LbfgsPoissonRegressionTrainer.Options(){L1Regularization=0.5633117F,L2Regularization=32768F,LabelColumnName=@"basesalary",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
