// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearning
{
    public partial class MLMSav
    {
        /// <summary>
        /// model input class for MLMSav.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"gun_name")]
            public string Gun_name { get; set; }

            [ColumnName(@"gun_archetype")]
            public string Gun_archetype { get; set; }

            [ColumnName(@"Source")]
            public string Source { get; set; }

            [ColumnName(@"Element")]
            public string Element { get; set; }

            [ColumnName(@"gun_RoF")]
            public float Gun_RoF { get; set; }

            [ColumnName(@"Rarity")]
            public string Rarity { get; set; }

            [ColumnName(@"weapon_type")]
            public string Weapon_type { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLMSav.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"gun_name")]
            public float[] Gun_name { get; set; }

            [ColumnName(@"gun_archetype")]
            public float[] Gun_archetype { get; set; }

            [ColumnName(@"Source")]
            public float[] Source { get; set; }

            [ColumnName(@"Element")]
            public float[] Element { get; set; }

            [ColumnName(@"gun_RoF")]
            public float Gun_RoF { get; set; }

            [ColumnName(@"Rarity")]
            public uint Rarity { get; set; }

            [ColumnName(@"weapon_type")]
            public float[] Weapon_type { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLMSav.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
