// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearning
{
    public partial class MLModelAbby
    {
        /// <summary>
        /// model input class for MLModelAbby.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Unnamed: 0")]
            public float Unnamed__0 { get; set; }

            [ColumnName(@"Company Name")]
            public string Company_Name { get; set; }

            [ColumnName(@"Location")]
            public string Location { get; set; }

            [ColumnName(@"Datum")]
            public string Datum { get; set; }

            [ColumnName(@"Detail")]
            public string Detail { get; set; }

            [ColumnName(@"Status Rocket")]
            public string Status_Rocket { get; set; }

            [ColumnName(@"Rocket")]
            public string Rocket { get; set; }

            [ColumnName(@"Status Mission")]
            public string Status_Mission { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelAbby.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Unnamed: 0")]
            public float Unnamed__0 { get; set; }

            [ColumnName(@"Company Name")]
            public float[] Company_Name { get; set; }

            [ColumnName(@"Location")]
            public float[] Location { get; set; }

            [ColumnName(@"Datum")]
            public string Datum { get; set; }

            [ColumnName(@"Detail")]
            public string Detail { get; set; }

            [ColumnName(@"Status Rocket")]
            public float[] Status_Rocket { get; set; }

            [ColumnName(@"Rocket")]
            public float[] Rocket { get; set; }

            [ColumnName(@"Status Mission")]
            public uint Status_Mission { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelAbby.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
